language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: p3SBDtiUS/BPdKn0n31oEuf+EKJ+sEEnYk0Do5AUnk2ZK53q7JzBPQs9ggxEirMqjc1195n6RApaMsyr1pPiocKdrz8xv8DDF0zpC8JjoGWhC32bi2se04uPkQVUGT1d1HAsnbnQr2Iq+oxLsdHPjJmpxkkQD7IocQwaqsGPJasn6Q36SN7jCoDTXmFeUzwnvCqMvf0vypQNv+7OfGzURe/jr98UQjimF1sQ3h+xjIvy34P/QvzDT9QOxojRgbhnQ79hL2urSSjRkHgjt63TcasKTPGUoNXbaRX7tO9UXAh5woe/SpKkOfNsJcXLoYsbN+/g7JqbLhg7fEh7kCyiSSz8DsaGypvgRn9kJlP03LfjWr2SEIpDzCcRRk1RGUouth1piu1wKdcaAHQ+meCn+wIoaQHuncNi2pO3s55TjqKQ43qGQAFyd/ximejYP79Gt2msDlNolbiRXU3K/+92I3ztds0O1ZeiEc9BR0VMXFLIR2GKOcMAd8oJcsnKooDYnSAddmQmoRDto6R4h96f31le++C1KYMy814uG9ddRA/rkrejBk6vLxfmWon33Y4Ar1NP5e8L57NOOcd2LZlUq/2NNdAlwPVJpNJZJbXRTVfbJmimD43eVOoQqbZudtfhUFej3ymRBnQuXycf/BHth5sRMNf0+7+W1wMDP+5+3qQ=
  app: mongo-blog-app
  on:
    repo: Onesun15/blog-app-mongo
